# NOTE: This file was generated via generate.sh. Don't edit it directly

name: Github CI

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  verify-templating:
    name: Verify templating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: make all
      - name: Check Git status
        run: |
          test -z "$(git status --short)"

  docker:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs:
      - verify-templating
    strategy:
      matrix:
        target:
          [
            "8.1.7-cli-bullseye",
            "8.1.7-fpm-bullseye",
            "8.1.7-nginx-bullseye",
            "8.1.7-cli-buster",
            "8.1.7-fpm-buster",
            "8.1.7-nginx-buster",
            "8.1.7-cli-alpine3.16",
            "8.1.7-fpm-alpine3.16",
            "8.1.7-nginx-alpine3.16",
            "8.1.7-cli-alpine3.15",
            "8.1.7-fpm-alpine3.15",
            "8.1.7-nginx-alpine3.15",
            "8.0.20-cli-bullseye",
            "8.0.20-fpm-bullseye",
            "8.0.20-nginx-bullseye",
            "8.0.20-cli-buster",
            "8.0.20-fpm-buster",
            "8.0.20-nginx-buster",
            "8.0.20-cli-alpine3.16",
            "8.0.20-fpm-alpine3.16",
            "8.0.20-nginx-alpine3.16",
            "8.0.20-cli-alpine3.15",
            "8.0.20-fpm-alpine3.15",
            "8.0.20-nginx-alpine3.15",
            "7.4.30-cli-bullseye",
            "7.4.30-fpm-bullseye",
            "7.4.30-nginx-bullseye",
            "7.4.30-cli-buster",
            "7.4.30-fpm-buster",
            "7.4.30-nginx-buster",
            "7.4.30-cli-alpine3.16",
            "7.4.30-fpm-alpine3.16",
            "7.4.30-nginx-alpine3.16",
            "7.4.30-cli-alpine3.15",
            "7.4.30-fpm-alpine3.15",
            "7.4.30-nginx-alpine3.15",
          ]
    env:
      ENABLE_DOCKERHUB: ${{ (secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN) && 'true' || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ env.ENABLE_DOCKERHUB == 'true' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/bake-action@v2
        with:
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name == 'push' }}
        if: ${{ env.ENABLE_DOCKERHUB == 'true' }}
      - name: Build and push to GitHub Container Registry
        uses: docker/bake-action@v2
        env:
          REGISTRY: ghcr.io
          REPO: ${{ github.repository_owner }}/php
        with:
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name == 'push' }}
